# Generated by Django 4.0.6 on 2023-05-12 17:19

from django.db import migrations, models
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlestorage',
            name='com_end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='articlestorage',
            name='com_if_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articlestorage',
            name='com_limit',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='articlestorage',
            name='com_location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='articlestorage',
            name='com_start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='articlestorage',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
