# Generated by Django 4.0.6 on 2023-05-12 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_articlestorage_com_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlestorage',
            name='tags',
        ),
    ]
