# Generated by Django 4.0.6 on 2023-05-12 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_remove_articlestorage_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlestorage',
            options={'ordering': ['-created_time', 'author'], 'verbose_name': '活动', 'verbose_name_plural': '活动'},
        ),
    ]
