# Generated by Django 4.0.6 on 2023-05-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='author_permission',
            field=models.BooleanField(default=False, verbose_name='创建活动权限'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='comment_permission',
            field=models.BooleanField(default=False, verbose_name='评论权限'),
        ),
    ]
