# Generated by Django 4.0.6 on 2023-05-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_alter_articlestorage_options'),
        ('userprofile', '0002_alter_profile_author_permission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='collected_com',
            field=models.ManyToManyField(to='article.articlestorage'),
        ),
    ]
